name: Cluademail

options:
  bundleIdPrefix: com.cluademail
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: Cluademail
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "26.0"

configs:
  Debug:
    buildSettings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  Release:
    buildSettings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

configFiles:
  Debug: Cluademail/Resources/Configuration/Development.xcconfig
  Release: Cluademail/Resources/Configuration/Production.xcconfig

targets:
  Cluademail:
    type: application
    platform: macOS
    sources:
      - path: Cluademail
        excludes:
          - "**/*.xcconfig"
          - "MCP/Server/MCPMain.swift"
    resources:
      - path: Cluademail/Resources/Assets.xcassets
    dependencies:
      - target: CluademailMCP
        link: false
    postCompileScripts:
      - name: Embed and Install MCP Server
        script: |
          # Copy app bundle to /Applications first
          rm -rf "/Applications/${PRODUCT_NAME}.app"
          cp -R "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app" "/Applications/"

          # Copy MCP binary into installed app bundle
          cp "${BUILT_PRODUCTS_DIR}/cluademail-mcp" "/Applications/${PRODUCT_NAME}.app/Contents/MacOS/cluademail-mcp"

          # Re-sign the MCP binary
          codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY:-"-"}" --preserve-metadata=entitlements "/Applications/${PRODUCT_NAME}.app/Contents/MacOS/cluademail-mcp"
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cluademail.app
        INFOPLIST_FILE: Cluademail/Supporting/Info.plist
        CODE_SIGN_ENTITLEMENTS: Cluademail/Supporting/Cluademail.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        # Google OAuth credentials
        GOOGLE_CLIENT_ID: 745260212298-e59afp5voo9f53arm4qfa6oogn09gbkh.apps.googleusercontent.com
        GOOGLE_REVERSED_CLIENT_ID: com.googleusercontent.apps.745260212298-e59afp5voo9f53arm4qfa6oogn09gbkh
      configs:
        Debug:
          # Allow ad-hoc signing for development without a team
          CODE_SIGN_IDENTITY: "-"
          ENABLE_HARDENED_RUNTIME: NO
        Release:
          ENABLE_HARDENED_RUNTIME: YES

  CluademailTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CluademailTests
    dependencies:
      - target: Cluademail
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cluademail.app.tests
        PRODUCT_MODULE_NAME: CluademailTests
        INFOPLIST_FILE: CluademailTests/Info.plist
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Cluademail.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Cluademail

  CluademailUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: CluademailUITests
    dependencies:
      - target: Cluademail
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cluademail.app.uitests
        PRODUCT_MODULE_NAME: CluademailUITests
        INFOPLIST_FILE: CluademailUITests/Info.plist
        TEST_TARGET_NAME: Cluademail

  CluademailMCP:
    type: tool
    platform: macOS
    sources:
      # MCP server code
      - path: Cluademail/MCP
      # Shared Core code (models, services, etc.)
      - path: Cluademail/Core
        excludes:
          # Exclude services that depend on AppState or UI components
          - "Services/Sync/SyncCoordinator.swift"
          - "Services/Sync/SyncEngine.swift"
          - "Services/Sync/SyncScheduler.swift"
          - "Services/Sync/SyncLock.swift"
          - "Services/DatabaseService.swift"
          - "Services/NotificationService.swift"
          - "Services/EmailDetail/CIDResolver.swift"
          - "Services/EmailDetail/HTMLSanitizer.swift"
      # App configuration
      - path: Cluademail/App/AppConfiguration.swift
    settings:
      base:
        PRODUCT_NAME: cluademail-mcp
        PRODUCT_BUNDLE_IDENTIFIER: com.cluademail.mcp
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        # Google OAuth credentials (same as main app)
        GOOGLE_CLIENT_ID: 745260212298-e59afp5voo9f53arm4qfa6oogn09gbkh.apps.googleusercontent.com
        GOOGLE_REVERSED_CLIENT_ID: com.googleusercontent.apps.745260212298-e59afp5voo9f53arm4qfa6oogn09gbkh
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          ENABLE_HARDENED_RUNTIME: NO
        Release:
          ENABLE_HARDENED_RUNTIME: YES

schemes:
  Cluademail:
    build:
      targets:
        Cluademail: all
        CluademailMCP: all
        CluademailTests: [test]
        CluademailUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CluademailTests
        - CluademailUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  CluademailMCP:
    build:
      targets:
        CluademailMCP: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
